name: NodeJS service docker image build

on:
  workflow_call:
    inputs:
      enable-code-scans:
        required: false
        type: boolean
      node-app-path:
        required: true
        type: string
      k8s-microservice-name:
        required: true
        type: string
      k8s-namespace:
        required: true
        type: string
    secrets:
      ghcr-token:
        required: true
        description: Github token allowing access to the libraries and ghcr.
      drone-server:
        required: true
        description: Drone server url.
      drone-token:
        required: true
        description: Drone token.

env:
  ENABLE_CODE_SCANS: ${{ inputs.enable-code-scans }}

jobs:
  # This job is responsible for preparation of the build
  # environment variables.
  prepare:
    name: Preparing build context
    runs-on: ubuntu-20.04
    outputs:
      SANITISED_REPOSITORY_NAME: ${{ steps.get_env.outputs.SANITISED_REPOSITORY_NAME }}
      DOCKER_IMAGE: ${{ steps.get_env.outputs.DOCKER_IMAGE }}
      GITHUB_COMMIT_NUMBER: ${{ steps.get_env.outputs.GITHUB_COMMIT_NUMBER }}
      GITHUB_SHA: ${{ steps.get_env.outputs.GITHUB_SHA }}
      DOCKER_IMAGE_SEMVER: ${{ steps.semver.outputs.semantic_version }}
      WORKING_DIRECTORY: ${{ steps.get_env.outputs.WORKING_DIRECTORY }}
      CHECK_IF_MASTER_BRANCH: ${{ steps.get_env.outputs.CHECK_IF_MASTER_BRANCH }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set environment variables
        id: get_env
        run: |
          TMP_SANITISED_REPOSITORY_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's|\.|-|g')
          TMP_GITHUB_COMMITS_COUNT=$(git rev-list --count HEAD)
          TMP_GITHUB_COUNT_NUMBER=$(echo ${GITHUB_RUN_NUMBER})
          echo "SANITISED_REPOSITORY_NAME=$TMP_SANITISED_REPOSITORY_NAME" > $GITHUB_OUTPUT
          echo "DOCKER_IMAGE=$(echo ghcr.io/${{ github.repository_owner }}/$TMP_SANITISED_REPOSITORY_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "GITHUB_COMMIT_NUMBER=$TMP_GITHUB_COMMITS_COUNT" >> $GITHUB_OUTPUT
          echo "GITHUB_SHA=$(echo ${GITHUB_SHA::8})" >> $GITHUB_OUTPUT
          echo "GITHUB_RUN_ID=$TMP_GITHUB_COUNT_NUMBER" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=$TMP_RELEASE_VERSION" >> $GITHUB_OUTPUT

          [ -d "website/" ] && cd website/ || cd ${{ inputs.node-app-path }}
          echo "WORKING_DIRECTORY=$(pwd)" >> $GITHUB_OUTPUT
          # Check if it's master or main branch
          currentBranch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$currentBranch" = "master" ] || [ "$currentBranch" = "main" ]; then
            echo "CHECK_IF_MASTER_BRANCH=true" >> $GITHUB_OUTPUT
          else
            echo "CHECK_IF_MASTER_BRANCH=false" >> $GITHUB_OUTPUT
          fi

      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: semver.yaml
          repository_local: true
          github_username: ${{ github.ACTOR }}
          github_token: $GHCR_TOKEN

      - name: Semver check
        run: |
          echo "Semantic version detected: ${{ steps.semver.outputs.semantic_version }}"

  build-local:
    needs: [prepare]
    name: Building node application locally
#     runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ needs.prepare.outputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Move package and yarn if necessary
        run: |
          if [[ "${{ needs.prepare.outputs.WORKING_DIRECTORY }}" =~ \/website$ ]]; then
            cp package.json ../ || true
            cp yarn.lock ../ || true
          fi
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            disr/ssr/node_modules
            /tmp/.buildx-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys:
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          # yarn install --network-timeout 1000000000 --ignore-optional --ignore-engines --link-duplicates --check-files
          yarn --prefer-offline --network-timeout 1000000000 --ignore-optional --ignore-engines --link-duplicates --check-files
          yarn global add @quasar/cli --network-timeout 1000000000

      - name: Inject additional metadata
        run: |
          printf "\nMETADATA_VERSION=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}\nMETADATA_COMMIT=${{ needs.prepare.outputs.GITHUB_SHA }}\nMETADATA_BUILD=$GITHUB_RUN_NUMBER/$GITHUB_REF_NAME $(date +'%d/%m/%H%M')\n" >> .env

      - name: Build the application
        run: |
          quasar -v
          quasar build -m ssr

      - name: Copy certificates
        run: |
          cp -r certs ${{ inputs.node-app-path }}/ || true

      - name: Install SSR app dependencies
        run: |
          cd dist/ssr
          NODE_ENV=production yarn --prefer-offline --network-timeout 1000000000 --ignore-optional --ignore-engines --check-files

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.ghcr-token }}
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
          tags: "${{ needs.prepare.outputs.DOCKER_IMAGE  }}:${{ needs.prepare.outputs.GITHUB_SHA }},${{ needs.prepare.outputs.DOCKER_IMAGE }}:${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }},${{ needs.prepare.outputs.DOCKER_IMAGE  }}:latest"
          build-args: |
            ACCESS_TOKEN=${{ secrets.ghcr-token }}
            ACCESS_USERNAME=${{ github.actor }}
            MICROSERVICE_NAME=${{ github.event.repository.name }}
            METADATA_GITHUB_SHA=${{ needs.prepare.outputs.GITHUB_SHA }}
            METADATA_BUILD_NUMBER="$GITHUB_RUN_ID/$GITHUB_REF_NAME/$(date +'%d/%m/%Y %H:%M')"
            METADATA_VERSION=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}
          file: Dockerfile-ci
          context: ${{ needs.prepare.outputs.WORKING_DIRECTORY }}
          labels: "org.opencontainers.image.revision=${{ needs.prepare.outputs.GITHUB_SHA }},org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ'),org.opencontainers.image.version=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }},com.github.repo.branch=$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')"
          no-cache: false
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ghcr-token }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ prepare, build-local ]
    if: needs.prepare.outputs.CHECK_IF_MASTER_BRANCH == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get list of the commits since last release
        run: |
          printf "$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")" > .release_notes
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}
          body_path: .release_notes
          token: ${{ secrets.ghcr-token }}
          tag_name: v${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}
          prerelease: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

  deploy:
    name: Deploy to dev cluster
    runs-on: ubuntu-latest
    needs: [ prepare, build-local, release ]
    if: needs.prepare.outputs.CHECK_IF_MASTER_BRANCH == 'true'
    env:
      DRONE_SERVER: ${{ secrets.drone-server }}
      DRONE_TOKEN: ${{ secrets.drone-token }}
    steps:
      - name: Install drone client
        run: |
          curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
          sudo install -t /usr/local/bin drone
      - name: Run deployment
        run: |
          drone build create --param IMAGE_VERSION=${{ needs.prepare.outputs.DOCKER_IMAGE }}:${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }} --param IMAGE_SEMVER=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }} --param IMAGE_NAMESPACE=${{ inputs.k8s-namespace }} ${{ github.repository }}